# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
    contents: read
    checks: write
    id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B  --no-transfer-progress package -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -P github --file pom.xml
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3.7.6
      with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          fail_on_failure: true


  publish-snapshot:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B --no-transfer-progress deploy -DskipTests -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -P github
      env:
        GITHUB_TOKEN: ${{ github.token }}
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
